INSERT INTO PRODUCT (name, price) VALUES ('BMV', 100);
INSERT INTO PRODUCT (name, price) VALUES ('Tesla', 200);
INSERT INTO PRODUCT (name, price) VALUES ('Tesla Roadster', 300);

INSERT INTO CATEGORY (name, description) VALUES ('Cars', 'Cars category');
INSERT INTO CATEGORY (name, description) VALUES ('Ships', 'Ships category');

INSERT INTO PRODUCT_CATEGORY_RELATION (PRODUCT_ID, CATEGORY_ID) VALUES (1,1);
INSERT INTO PRODUCT_CATEGORY_RELATION (PRODUCT_ID, CATEGORY_ID) VALUES (1,2);

